//User Action types
export const STORY_SUMMARY = 'STORY_SUMMARY';
export const STORY_DESCRIPTION = 'STORY_DESCRIPTION';
export const STORY_TYPE = 'STORY_TYPE';
export const STORY_COMPLEXITY = 'STORY_COMPLEXITY';
export const ESTIMATED_TIME = 'ESTIMATED_TIME';
export const COST_ASSOCIATED = 'COST_ASSOCIATED';

//Admin Action types
export const GET_STORIES_FAIL = 'GET_STORIES_FAIL';
export const GET_STORIES_PASS = 'GET_STORIES_PASS';
export const ACCEPT_STORIES = 'ACCEPT_STORIES';
export const REJECT_STORIES = 'REJECT_STORIES';
